name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
    
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/core:2.9
      - uses: actions/checkout@v2
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=readers/dist/programmeren_gevorderd_csharp.pdf
            readers/programmeren_gevorderd_csharp/programmeren_gevorderd_csharp.md
